# Generated by Django 4.2.8 on 2024-03-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dbPereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True)),
                ('images', models.JSONField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending', 'В обработке'), ('resolved', 'Завершен'), ('accepted', 'Принят'), ('rejected', 'Отменен')], default='new', max_length=20)),
            ],
            options={
                'db_table': 'dbpereval_added',
            },
        ),
    ]
