# Generated by Django 4.2.8 on 2024-03-27 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbpereval', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dbpereval',
            table='pereval_added',
        ),
    ]
